### ISSUE TITLE
Update Map Legend Labels

### ISSUE THREAD

**Issue by crvanpollard** [dvrpc/TCDI#7]
Change legend labels to
small = $8,000
medium =  $10,000
large = $15,000

@mmolta not sure where to edit/update this item within the existing codebase in this repo.

**Comment by crvanpollard** [comment]
<img width="715" alt="Screen Shot 2022-06-16 at 6 29 23 PM" src="https://user-images.githubusercontent.com/4401281/174189041-8516a5d2-52f3-4ed2-aab7-5ff0bbf7e7b4.png">

**Comment by DVRPCfreight** [comment]
The legend builds dynamically. There is no need to update the legend as the award amount is rendering correctly.

**Comment by crvanpollard** [comment]
hahaha I was missing a zero when reading the legend in ArcMap.
